version: '2'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  php:
    user: 1000:1000
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
volumes:
  mysql:
